services:
  app:
    container_name: sioapp
    image: node
    volumes:
      - ./:/src
    working_dir: /src
    tty: true
    stdin_open: true
    ports:
      - 80:80
    depends_on:
      - redis
    environment:
      NODE_ENV: local
    networks:
      ws-network:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      ws-network:

networks:
  ws-network:
    external: true
